# Generated by Django 2.0.3 on 2018-03-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
