"""Using as facade for the entire app"""

from pythonpro.modules.models.modules import (
    ALL as ALL_MODULES,
    PYTHONIC_OBJECTS,
    PYTHON_BIRDS,
    PYTOOLS,
    PYTHON_FOR_PYTHONISTS,
    PYTHON_PATTERNS, PYTHON_WEB,
    TECH_INTERVIEW
)

ALL_MODULES
PYTHON_BIRDS
PYTHONIC_OBJECTS
PYTOOLS
PYTHON_FOR_PYTHONISTS
PYTHON_PATTERNS
PYTHON_WEB
TECH_INTERVIEW
