version: "3.3"

services:
  database:
    container_name: pythonpro_database
    image: postgres:15.2
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=pythonpro
      - POSTGRES_USER=pythonpro
    ports:
      - 5432:5432
  celery_broker:
    container_name: pythonpro_celery_broker
    image: rabbitmq:3.8.2
    ports:
      - 5672:5672
  redis:
    container_name: pythonpro_redis
    image: redis:5.0.7
    ports:
      - 6379:6379
