[tool.towncrier]
package = "changes"
directory = "changes/"
filename = "CHANGELOG.rst"
title_format = "{version} ({project_date})"
issue_format = "`#{issue} <https://github.com/pythonprobr/pythonpro-website/issues/{issue}>`_" 