# Generated by Django 2.2.2 on 2019-06-10 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0010_auto_20190226_1830'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('topic_duration', models.IntegerField(verbose_name='Duração do Tópico')),
                ('total_watched_time', models.IntegerField(verbose_name='Tempo assistindo o Tópico')),
                ('max_watched_time', models.IntegerField(verbose_name='Tempo até onde assistiu')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='topicinteraction',
            index=models.Index(fields=['user', 'topic', '-creation'], name='dashboard_t_user_id_39ea24_idx'),
        ),
        migrations.AddIndex(
            model_name='topicinteraction',
            index=models.Index(fields=['-creation'], name='dashboard_t_creatio_11d7b3_idx'),
        ),
    ]
