# Generated by Django 2.2.4 on 2019-08-12 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicinteraction',
            options={'verbose_name': 'Interação', 'verbose_name_plural': 'Interações'},
        ),
    ]
