# Generated by Django 3.1.2 on 2020-10-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='meta',
            field=models.JSONField(),
        ),
    ]
