# Generated by Django 4.2.1 on 2023-05-03 23:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0002_auto_20201007_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.DeleteModel(
            name='PageView',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
