# Generated by Django 3.0.4 on 2020-03-16 20:26

from django.db import migrations


def setup_payment_configs(apps, schema_editor):
    PagarmeFormConfig = apps.get_model('django_pagarme', 'PagarmeFormConfig')
    PagarmeItemConfig = apps.get_model('django_pagarme', 'PagarmeItemConfig')
    print()
    setup_payment_configs_function(PagarmeFormConfig, PagarmeItemConfig)


def setup_payment_configs_function(PagarmeFormConfig, PagarmeItemConfig):
    """"""
    free_interest_config = PagarmeFormConfig(
        name='Cartão ou Boleto 10 vezes sem juros',
        max_installments=10,
        default_installment=10,
        free_installment=10,
        interest_rate=0,
        payments_methods='credit_card,boleto',
    )
    free_interest_config.save()

    python_avancado = PagarmeItemConfig(
        name='Pacote Python Avançado - 50% de Desconto',
        slug='pacote-proximo-nivel-67-discount',
        price=49700,
        tangible=False,
        default_config=free_interest_config
    )
    python_avancado.save()

    PagarmeItemConfig.objects.filter(slug__startswith='bootcamp').update(upsell=python_avancado.id)


class Migration(migrations.Migration):
    dependencies = [
        ('checkout', '0004_bootcamp_setup'),
        ('django_pagarme', '0002_pagarmeitemconfig_upsell'),
    ]

    operations = [
        migrations.RunPython(setup_payment_configs, migrations.RunPython.noop)
    ]
