# Generated by Django 3.0.4 on 2020-03-16 20:26

from django.db import migrations


def setup_payment_configs(apps, schema_editor):
    PagarmeFormConfig = apps.get_model('django_pagarme', 'PagarmeFormConfig')
    PagarmeItemConfig = apps.get_model('django_pagarme', 'PagarmeItemConfig')
    print()
    setup_payment_configs_function(PagarmeFormConfig, PagarmeItemConfig)


def setup_payment_configs_function(PagarmeFormConfig, PagarmeItemConfig):
    """"""
    webinar_slug = 'treinamento-devpro-webinar-boleto'
    config_card_and_boleto = PagarmeFormConfig.objects.first()
    webinar_config = PagarmeItemConfig(
        name='Treinamento DevPro com 30% de Desconto',
        slug=webinar_slug,
        price=99700,
        tangible=False,
        default_config=config_card_and_boleto
    )
    webinar_config.save()

    webserie_config = PagarmeItemConfig(
        name='Treinamento DevPro com 30% de Desconto',
        slug='treinamento-devpro-webserie',
        price=99700,
        tangible=False,
        default_config=config_card_and_boleto
    )
    webserie_config.save()

    webserie_config = PagarmeItemConfig(
        name='Treinamento DevPro com 30% de Desconto',
        slug='treinamento-devpro-webserie-boleto',
        price=99700,
        tangible=False,
        default_config=config_card_and_boleto
    )
    webserie_config.save()

    masterclass_oto_config = PagarmeItemConfig(
        name='Treinamento DevPro com 30% de Desconto',
        slug='treinamento-devpro-masterclass-oto',
        price=99700,
        tangible=False,
        default_config=config_card_and_boleto
    )
    masterclass_oto_config.save()

    masterclass_oto_config = PagarmeItemConfig(
        name='Treinamento DevPro com 30% de Desconto',
        slug='treinamento-devpro-masterclass-oto-boleto',
        price=99700,
        tangible=False,
        default_config=config_card_and_boleto
    )
    masterclass_oto_config.save()


class Migration(migrations.Migration):
    dependencies = [
        ('checkout', '0006_webinar_setup'),
    ]

    operations = [
        migrations.RunPython(setup_payment_configs, migrations.RunPython.noop)
    ]
