# Generated by Django 3.2.4 on 2021-06-05 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('django_pagarme', '0004_pagarme_item_config_available_until'),
        ('memberkit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptiontype',
            options={'verbose_name': 'Tipo de Assinatura', 'verbose_name_plural': 'Tipos de Assinaturas'},
        ),
        migrations.CreateModel(
            name='PaymentItemConfigToSubscriptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                      related_name='subscription_type_relation',
                                                      to='django_pagarme.pagarmeitemconfig')),
                ('subscription_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_items_relation',
                                   to='memberkit.subscriptiontype')),
            ],
        ),
    ]
