# Generated by Django 3.2.4 on 2021-06-05 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('django_pagarme', '0004_pagarme_item_config_available_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memberkit', '0002_create_relationship_with_payment_config_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observation', models.TextField(blank=True, default='', verbose_name='Observação')),
                ('payment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                                 to='django_pagarme.pagarmepayment')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                                  related_name='created_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('subscriber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                                 related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('subscription_types',
                 models.ManyToManyField(related_name='subscriptions', to='memberkit.SubscriptionType')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
            },
        ),
    ]
