# Generated by Django 3.2.4 on 2021-06-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('memberkit', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='activated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='memberkit_user_id',
            field=models.IntegerField(null=True),
        ),
    ]
