# Generated by Django 3.2.4 on 2021-06-10 00:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('memberkit', '0004_add_membership_activation_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='discourse_groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=list,
                                                            size=None),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='email_marketing_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=list,
                                                            size=None),
        ),
    ]
