# Generated by Django 3.2.4 on 2021-06-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberkit', '0005_create_tags_for_discourse_email_marketing_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='include_on_cohort',
            field=models.BooleanField(default=False, verbose_name='Incluir na última turma'),
        ),
    ]
