# Generated by Django 3.2.7 on 2021-09-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('memberkit', '0007_allow_subscripiton_be_saved_without_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='days_of_access',
            field=models.IntegerField(default=73000),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='days_of_access',
            field=models.IntegerField(default=73000),
        ),
    ]
