# Generated by Django 4.0.4 on 2022-05-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('memberkit', '0008_added_days_of_access_field')]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='days_of_access',
            field=models.IntegerField(default=365),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='days_of_access',
            field=models.IntegerField(default=365),
        ),
    ]
