# Generated by Django 4.1 on 2022-09-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('memberkit', '0009_altered_subscription_default_to_one_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='has_discord_access',
            field=models.BooleanField(default=False),
        ),
    ]
