# Generated by Django 4.1.7 on 2023-03-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('memberkit', '0010_added_has_discord_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('A', 'Ativa'), ('I', 'Inativa')], max_length=1),
        ),
    ]
