# Generated by Django 4.1.7 on 2023-04-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('memberkit', '0011_alter_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='expired_at',
            field=models.DateField(null=True),
        ),
    ]
