# Generated by Django 4.1.7 on 2023-04-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('memberkit', '0013_populate_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='days_of_access',
            field=models.IntegerField(db_column='days_of_access', default=365),
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='days_of_access',
            new_name='old_days_of_access',
        ),
    ]
