# Generated by Django 3.0.4 on 2020-04-22 00:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('redirector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='redirect',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RedirectLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('url', models.URLField()),
                ('redirect', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='redirector.Redirect')),
            ],
        ),
    ]
