# Generated by Django 3.0.4 on 2020-04-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirector', '0002_auto_20200421_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='use_javascript',
            field=models.BooleanField(default=False),
        ),
    ]
