# Generated by Django 3.0.4 on 2020-04-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirector', '0003_redirect_use_javascript'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirectlink',
            name='total_access',
            field=models.BigIntegerField(default=0),
        ),
    ]
