# Generated by Django 4.2.10 on 2024-02-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0002_discord_user_created_at_desc_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('A', 'Ativa'), ('I', 'Inativa')], default='I', max_length=32)),
            ],
        ),
    ]
