# Generated by Django 2.0.3 on 2018-03-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('_module_slug', models.SlugField(
                    choices=[('python-birds', 'Python Birds'), ('objetos-pythonicos', 'Objetos Pythônicos'),
                             ('pytools', 'PyTools'), ('python-para-pythonistas', 'Python para Pythonistas'),
                             ('python-web', 'Python Web'), ('python-patterns', 'Python Patterns'),
                             ('entrevistas-tecnicas', 'Entrevistas Técnicas')])),
            ],
            options={
                'db_table': 'sections_section',
                'ordering': ['_module_slug', 'order'],
            },
        ),
    ]
