# Generated by Django 2.0.3 on 2018-03-14 20:45

import django.db.models.deletion
from django.db import migrations, models


def populate_foreign_key(apps, scheme_editor):
    """Populate module foreign key attribute based on _module_slug"""
    Section = apps.get_model('modules', 'Section')
    Module = apps.get_model('modules', 'Module')
    for section in Section.objects.all():
        section.module = Module.objects.filter(slug=section._module_slug).get()
        section.save()


def reverse_populate_foreign_key(apps, scheme_editor):
    """No need to revert since column will be dropped. Function is present only to allow migration roll back"""


class Migration(migrations.Migration):
    dependencies = [
        ('modules', '0003_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='modules.Module'),
            preserve_default=False,
        ),
        migrations.RunPython(populate_foreign_key, reverse_populate_foreign_key)
    ]
