# Generated by Django 2.0.3 on 2018-03-18 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('vimeo_id', models.CharField(max_length=11)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.Chapter')),
            ],
            options={
                'ordering': ['chapter', 'order'],
            },
        ),
    ]
