# Generated by Django 2.0.3 on 2018-03-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('modules', '0007_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='discourse_topic_id',
            field=models.CharField(default='1', max_length=11),
        ),
    ]
