# Generated by Django 2.0.3 on 2018-03-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('modules', '0008_topic_discourse_topic_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='discourse_topic_id',
            field=models.CharField(max_length=11),
        ),
    ]
