# Generated by Django 3.0.2 on 2020-01-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0010_auto_20190226_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
