# Generated by Django 3.2.3 on 2021-05-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('modules', '0011_created_duration_on_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='memberkit_url',
            field=models.URLField(blank=True, default='', max_length=1024),
        ),
    ]
