# Generated by Django 2.0.6 on 2018-06-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0004_cohortstudent_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohortstudent',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
