# Generated by Django 2.1.7 on 2019-02-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0005_auto_20180612_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='description',
            field=models.TextField(default='Alterar'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='discourse_topic_id',
            field=models.CharField(default=726, max_length=11),
        ),
        migrations.AddField(
            model_name='webinar',
            name='image',
            field=models.ImageField(null=True, upload_to='webinars/'),
        ),
    ]
