# Generated by Django 2.1.7 on 2019-03-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0007_auto_20190226_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='description',
            field=models.TextField(blank=True, default='Aula Pendente'),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='discourse_topic_id',
            field=models.CharField(default='726', max_length=11, null=True),
        ),
    ]
