# Generated by Django 3.2 on 2021-05-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0008_auto_20190307_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinar',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
