# Generated by Django 2.0.5 on 2018-06-01 14:08

from django.db import migrations
import pythonpro.core.managers


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180530_1826'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', pythonpro.core.managers.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
