# Generated by Django 2.2.4 on 2019-08-12 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0007_auto_20190705_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(
                    choices=[('BECOME_LEAD', 'User become lead'), ('ACTIVATED', 'User Watched first video class'),
                             ('CLIENT_LP', 'User visited Client Landing Page'),
                             ('CLIENT_CHECKOUT', 'User clicked on client checkout button'),
                             ('CLIENT_BOLETO', 'User generated a Client Boleto'),
                             ('BECOME_CLIENT', 'User become client'), ('MEMBER_LP', 'User visited Member Landing Page'),
                             ('MEMBER_CHECKOUT', 'User clicked on Member checkout Button'),
                             ('MEMBER_BOLETO', 'User generate Member Boleto'),
                             ('WAITING_LIST', 'User subscribed to Waiting List'),
                             ('BECOME_MEMBER', 'User Become Client')], max_length=32)),
                ('source', models.CharField(blank=True, help_text='Traffic source origin', max_length=32, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Usuário',
                'verbose_name_plural': 'Históricos de Usuários',
            },
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['user', 'creation'], name='core_userin_user_id_6dabfb_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['category', '-creation'], name='core_userin_categor_d6027e_idx'),
        ),
    ]
