# Generated by Django 2.2.6 on 2019-10-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0008_auto_20190812_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinteraction',
            name='category',
            field=models.CharField(
                choices=[('BECOME_LEAD', 'User become Lead'), ('ACTIVATED', 'User Watched first video class'),
                         ('CLIENT_LP', 'User visited Client Landing Page'),
                         ('CLIENT_CHECKOUT', 'User clicked on Client checkout button'),
                         ('CLIENT_BOLETO', 'User generated a Client Boleto'), ('BECOME_CLIENT', 'User become Client'),
                         ('MEMBER_LP', 'User visited Member Landing Page'),
                         ('MEMBER_CHECKOUT', 'User clicked on Member checkout Button'),
                         ('MEMBER_BOLETO', 'User generate Member Boleto'),
                         ('WAITING_LIST', 'User subscribed to Waiting List'), ('BECOME_MEMBER', 'User Become Member'),
                         ('LAUNCH_LP', 'User visited Launch Landing Page'),
                         ('LAUNCH_SUBSCRIPTION', 'User subscribed to launch'), ('CPL1', 'User Visited CPL1'),
                         ('CPL2', 'User Visited CPL2'), ('CPL3', 'User Visited CPL3')], max_length=32),
        ),
    ]
