# Generated by Django 3.0.3 on 2020-02-28 11:30

from django.db import IntegrityError, migrations

from django.db.transaction import atomic


def normalize_email(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    User = apps.get_model('core', 'User')
    print()
    for msg in normalize_all_users_email(User):
        print(msg)


def normalize_all_users_email(User):
    for user in User.objects.order_by('id').all():
        original_email = user.email
        normalized_email = user.email.lower()
        if normalized_email != original_email:
            user.email = normalized_email
            try:
                with atomic():
                    user.save()
            except IntegrityError:
                yield f'Normalization error user {user.id}, {original_email}'


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0009_auto_20191031_1324'),
    ]

    operations = [
        migrations.RunPython(normalize_email, migrations.RunPython.noop)
    ]
